THEMES = {
    "dark": {
        "name": "🌙 深色主题",
        "bg_primary": "#0f172a",
        "bg_secondary": "#1e293b",
        "bg_tertiary": "#334155",
        "text_primary": "#f1f5f9",
        "text_secondary": "#94a3b8",
        "accent_blue": "#3b82f6",
        "accent_green": "#22c55e",
        "accent_red": "#ef4444",
        "accent_yellow": "#f59e0b",
        "accent_purple": "#8b5cf6",
        "border": "#334155",
    },
    "light": {
        "name": "☀️ 浅色主题",
        "bg_primary": "#f8fafc",
        "bg_secondary": "#ffffff",
        "bg_tertiary": "#e2e8f0",
        "text_primary": "#1e293b",
        "text_secondary": "#64748b",
        "accent_blue": "#3b82f6",
        "accent_green": "#22c55e",
        "accent_red": "#ef4444",
        "accent_yellow": "#f59e0b",
        "accent_purple": "#8b5cf6",
        "border": "#e2e8f0",
    },
    "ocean": {
        "name": "🌊 海洋主题",
        "bg_primary": "#0c4a6e",
        "bg_secondary": "#075985",
        "bg_tertiary": "#0369a1",
        "text_primary": "#f0f9ff",
        "text_secondary": "#bae6fd",
        "accent_blue": "#38bdf8",
        "accent_green": "#34d399",
        "accent_red": "#fb7185",
        "accent_yellow": "#fcd34d",
        "accent_purple": "#c4b5fd",
        "border": "#0369a1",
    },
}
